In [16]:
#finding second largest number
l = list(map(int,input().split(' ')))
l.sort()
print(l[-2])

 1 2 3 4 5


4


In [30]:
#number is prime or not
num = 17
prime = True
if num <= 1:
    prime = False
else:
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            prime = False
            break
if prime:
    print(num, "is Prime")
else:
    print(num, "is not Prime")

17 is Prime


In [22]:
#reverse a string
s = input()
res = ""
for i in range(-1,-len(s)-1,-1):
    res+=s[i]
print(res)

 12


21


In [31]:
#merge two sorted arrays
L1 = [1,2,3,4,5]
L2 = [6,7,8,9,10]
L1.extend(L2)
L1.sort()
print(L1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [34]:
#factorial
def fact(n):
    if n==0 or n==1:
        return 1
    else:
        return n*fact(n-1)
print(fact(int(input())))

 4


24


In [35]:
#polindrome
s = input()
if s==s[::-1]:
    print("Polindrome")
else:
    print("Not Polindrome")

 12


Not Polindrome


In [36]:
#decimal number to binary
def binary(n):
    res = ""
    while(n!=0):
        res = str(n%2)+res
        n=n//2
    print(res)
n = binary(int(input()))

 12


1100


In [47]:
#find pairs in an array
l = [1,2,3,4,5,6,7]
Sum = 9
for j in range(len(l)-1):
    for i in range(1,len(l)):
        if l[j]+l[i]==Sum:
            print([l[j],l[i]])

[2, 7]
[3, 6]
[4, 5]
[5, 4]
[6, 3]


In [37]:
#count the frequency of the elements
L = [1,2,3,4,5]
L2 = list(set(L))
for el in L2:
    print(f"{el}:{str(L.count(el))}")

1:1
2:1
3:1
4:1
5:1


In [3]:
#fibonocci
def fib(n):
    if n==0 or n==1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

def series(s):
    for i in range(s):
        res = fib(i)
        print(res)
n=int(input())
series(n)

 5


1
1
2
3
5


In [39]:
#remove duplicates from a list
L = [1,2,3,3,4,4,5]
print(list(set(L)))

[1, 2, 3, 4, 5]


In [41]:
#anagram check
s1 = "gum"
s2 = "mug"
print(str(sorted(s1)).lower()==str(sorted(s2)).lower())

True


In [1]:
#count vowels and consonants
s = "we have a meeting"
vowel_count = 0
consonant_count = 0
s = str(''.join(s.split()))
for ch in s:
    if ch in "aeiou":
        vowel_count+=1
    else:
        consonant_count+=1
print(f"vowel_count={vowel_count}")
print(f"consonant_count={consonant_count}")

vowel_count=7
consonant_count=7


In [5]:
#binary search
l = [4,5,5,8,1,6]
user = 17
lowest = 0
highest = len(l)-1
mid = highest+lowest//2
for ind in range(len(l)):
    if l[ind]<user:
        highest=mid-1
    elif l[ind]>user:
        lowest=mid+1
    elif l[ind]==user:
        print(ind)
        break
else:
    print(-1)

-1


In [6]:
#check if a list is sorted
l = [2,3,7,5,4]
for ind in range(len(l)-1):
    if l[ind]>l[ind+1]:
        l[ind],l[ind+1]=l[ind+1],l[ind]
print(l)

[2, 3, 5, 4, 7]


In [7]:
#transpose of matrix
import numpy as np
l = [[3,4,5], [6,5,4], [7,1,2]]
print(np.transpose(l))

[[3 6 7]
 [4 5 1]
 [5 4 2]]


In [12]:
#sum of digits in a number
def sum_digits(num):
    if num==0:
        return 0
    return num%10+sum_digits(num//10)
print(sum_digits(123))

6


In [10]:
#intersection of two list
L1 = [4,3,5,6,7]
L2 = [2,4,6,8,9]
L3 = []
for el in L1:
    if el in L2:
        L3.append(el)
print(L3)

[4, 6]


In [11]:
#permutations of a string
from itertools import permutations
s='abc'
print(list(permutations(s)))

[('a', 'b', 'c'), ('a', 'c', 'b'), ('b', 'a', 'c'), ('b', 'c', 'a'), ('c', 'a', 'b'), ('c', 'b', 'a')]
